In [2]:
from sympy import *

In [3]:
m0,m1,m2,m3 = symbols('m0 m1 m2 m3')
k0, k1, k2 = symbols('k0 k1 k2')

In [4]:
m0=m0+m3+k0
m1=m0+m1+k0
m2=m1+m2+k0
m3=m2+m3+k0

m0=m0+m3+k1
m1=m0+m1+k1
m2=m1+m2+k1
m3=m2+m3+k1

m0=m0+m3+k2
m1=m0+m1+k2
m2=m1+m2+k2
m3=m2+m3+k2



In [6]:
m0

19*k0 + 5*k1 + k2 + 7*m0 + 5*m1 + 4*m2 + 10*m3

In [100]:
m1

26*k0 + 7*k1 + 2*k2 + 10*m0 + 7*m1 + 5*m2 + 14*m3

In [101]:
m2

36*k0 + 10*k1 + 3*k2 + 14*m0 + 10*m1 + 7*m2 + 19*m3

In [102]:
m3

50*k0 + 14*k1 + 4*k2 + 19*m0 + 14*m1 + 10*m2 + 26*m3

In [29]:
print(m0)

k0 + m0 + m3


In [9]:
import numpy as np
def create_matrix(l):
    kl=1
    K=np.zeros((l,kl))
    M=np.zeros((l,l))
    for n in range(kl):
      for i in range(0,l):
        z=np.zeros((1,l))
        k=np.zeros((1,kl))
        k.itemset((0,n),1)
        if n==0:
            z.itemset((0,i),1)
        if n==0 and i==0:
            z.itemset((0,(i-1)%l),1)
        K[i]=K[i]+K[(i-1)%l]+k
        M[i]=M[i]+M[(i-1)%l]+z
#     print("key matrix")
#     print(K)
#     print("msg matrix")
#     print(M)
    return(M,K)

In [45]:
Z=np.linalg.inv(M)

In [5]:
def encrypt(key, msg):
    key = list(key)
    msg = [ord(i) for i in msg]
    for char_key in key:
        for i in range(len(msg)):
            if i == 0:
                tmp =  msg[i] + ord(char_key) + msg[-1]
            else:
                tmp = msg[i] + ord(char_key) + msg[i-1]
            while tmp > 255:
                tmp -= 256
            msg[i] = tmp
    return msg 

In [6]:
encrypt("\x0a\x14\x1a",''.join([chr(i) for i in [11,32,19,32,28,11,29,84,72,32]]))

[90, 18, 90, 92, 62, 21, 8, 117, 174, 221]

In [1]:
m="you liked my new encryption tool, pretty secure huh, anyway here is the key to the encrypted image from /var/backups/recovery: cB!6%sdH8Lj^@Y*$C2cf"
encrypt("\x0a\x14\x1a",m)

NameError: name 'encrypt' is not defined

In [11]:
M,K=create_matrix(10)
c=np.dot(M,np.array([11,32,19,32,28,11,29,84,72,32]))+np.dot(K,np.array([10]))
c

array([ 53.,  95., 124., 166., 204., 225., 264., 358., 440., 482.])

In [170]:
Z

array([[ 1.00000000e+00,  1.00000000e+00, -4.00000000e+00,
         6.00000000e+00, -3.00000000e+00],
       [-3.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        -4.00000000e+00,  3.00000000e+00],
       [ 3.00000000e+00, -3.00000000e+00,  1.00000000e+00,
         1.00000000e+00, -1.00000000e+00],
       [-1.00000000e+00,  3.00000000e+00, -3.00000000e+00,
         1.00000000e+00,  1.06581410e-14],
       [ 4.49640325e-15, -1.00000000e+00,  3.00000000e+00,
        -3.00000000e+00,  1.00000000e+00]])

array([[10.,  8.,  7.,  6.,  5.,  4., 13.],
       [13., 10.,  8.,  7.,  6.,  5., 17.],
       [17., 13., 10.,  8.,  7.,  6., 22.],
       [22., 17., 13., 10.,  8.,  7., 28.],
       [28., 22., 17., 13., 10.,  8., 35.],
       [35., 28., 22., 17., 13., 10., 43.],
       [43., 35., 28., 22., 17., 13., 53.]])

In [203]:
pow(2.71,3.14)

22.883559193263366

In [204]:
pow(3.14,2.71)

22.21668954600232

In [7]:
import binascii
q="cbd7a39b1a942c4cf60a3e05bc3258d5a20b8a0d7c8a3f0049c729f145832d97cb925c2f3bc3c7b279c65b77234d9215f732ca1bd17e90e759124027b6e7bc988a85e6b3a32c0588ebdbf45099ba40043586c06624f95c2a0172a277467fba9233b867ef58bf7dc96936f0b48bf47edf4b8ba959f0c58ea591ff27182581bf65e01f3ee0ae78dd6fe41f2b67dc192fb14bac063eff5eddcb56a5f71de2084eb06b8abf650a"
qq=binascii.unhexlify(q)


In [8]:
qq

b"\xcb\xd7\xa3\x9b\x1a\x94,L\xf6\n>\x05\xbc2X\xd5\xa2\x0b\x8a\r|\x8a?\x00I\xc7)\xf1E\x83-\x97\xcb\x92\\/;\xc3\xc7\xb2y\xc6[w#M\x92\x15\xf72\xca\x1b\xd1~\x90\xe7Y\x12@'\xb6\xe7\xbc\x98\x8a\x85\xe6\xb3\xa3,\x05\x88\xeb\xdb\xf4P\x99\xba@\x045\x86\xc0f$\xf9\\*\x01r\xa2wF\x7f\xba\x923\xb8g\xefX\xbf}\xc9i6\xf0\xb4\x8b\xf4~\xdfK\x8b\xa9Y\xf0\xc5\x8e\xa5\x91\xff'\x18%\x81\xbfe\xe0\x1f>\xe0\xaex\xddo\xe4\x1f+g\xdc\x19/\xb1K\xac\x06>\xff^\xdd\xcbV\xa5\xf7\x1d\xe2\x08N\xb0k\x8a\xbfe\n"

In [9]:
len(qq)

165

In [13]:
c=np.array([i for i in qq])

In [48]:
mm=np.dot(Z,c[-148:])

In [51]:
for i in range(255):
    #p=(mm)%256
    print(i)
    print(''.join([chr((int(j)-i)%256) for j in mm]))

0
\>¦{?¢ÎÊe’u;<u=‚šaZ8Á_î‹OR&Å&Fb»5¦¥
1
´ÀH}aÇS=©i3ÆÉÒ‡êÆL”«)D‚á:—Pµ¬Vq¸-æŽ0ÔÛñú`ÌïˆØ‚bï[H …Ã0P9¥½ÔbÍÖp/ÔÎ8:× „®‡hf½KŸÌ¹ÃÖh‰`k?¯–ÔÈëm'ð[=¥z>¡ÍÉd‘t:;t<™`Y7À^~íŠNQ%Ä%Eaº4¥¤
2
d}m³¿G|`ÆR<¨h2ÅÈÑ
†éÅK“ª(Cà9–O´«Up·,å/ÓÚðù_Ëî‡×aîZG„Â/O8¤¼ÓaÌÕo.ÓÍ79֟ƒ­†ge¼JžË¸ÂÕgˆ_j>®•ÓÇêl&ïZ<¤y= ÌÈcs9
:s;€˜_X6¿]}ì‰MP$Ã$D`¹3¤£
3
c|€l²¾F{_ÅQ;§g1ÄÇÐ	…èÄJ’©'B€ß8•N³ªTo¶+äŒ.ÒÙïø^Êí†Ö€`íYFƒÁ.N7£»Ò`ËÔn-ÒÌ68՞‚¬…fd»IÊ·ÁÔf‡^i=­”ÒÆék%î
Y;£x<ŸËÇbr8	9r:—^W5¾\|ëˆLO#Â#C_¸2£¢
4
b{k
±½Ez^ÄP:¦f0ÃÆÏ„çÃI‘¨&AÞ7”M²©Snµ*ã‹-ÑØî÷]Éì…Õ_ìXE‚À-M6¢ºÑ_ÊÓm,ÑË57ԝ«„ecºHœÉ¶ÀÓe†]h<¬“ÑÅèj$í	X:¢w;žÊÆaŽq78q9~–]V4½[{ê‡KN"Á"B^·1¢¡
5
Rm´)âŠ,Ð×íö\Èë„Ô~^ëWD¿,L5¡¹Ð^ÉÒl+ÐÊ46Ӝ€ªƒdb¹G›Èµ¿Òd…\g;«’ÐÄçi#ìW9¡v:ÉÅ`p67p8}•\U3¼Zzé†JM!À!A]¶0¡ 
6
`y}i¯»Cx\ÂN8¤d.ÁÄÍ‚þåÁG¦$?}Ü5’K°§Ql³(á‰+ÏÖìõ[ÇêƒÓ}]êVC€¾+K4 ¸Ï]ÈÑk*ÏÉ35қ©‚ca¸FšÇ´¾Ñc„[f:ª‘ÏÃæh"ëV8 u9œÈÄ_Œo56o7|”[T2»Yyè…IL ¿ @\µ/ Ÿ
7
_x|h®ºBw[ÁM7£c-ÀÃ́ýäÀFŽ¥#>|Û4‘J¯¦Pk²'àˆ*ÎÕëôZÆé‚Ò|\éUB½*J3Ÿ·Î\ÇÐj)ÎÈ24њ~¨b`·E™Æ³½Ð

In [67]:
c=np.array([i for i in qq])
for l in range(100,len(qq)):
    M=create_matrix(l)
    Z=np.linalg.inv(M)
    mm=np.dot(Z,c[len(qq)-l:len(qq)])
    mm[mm<0]+=256
    print(mm)
    tmp=''.join([chr((int(j)-116)%256) for j in mm])
    print(l)
    print(tmp)

[224.  97. 205. 240. 137. 217. 131.  99. 240.  25.  92.  73.  33. 134.
 196.  49.  81.  58. 166. 190. 213.  99. 206. 215. 113.  48. 213. 207.
  57.  59. 216. 161. 133. 175. 136. 105. 103. 190.  76. 160. 205. 186.
 196. 215. 105. 138.  97. 108.  64.  30. 176. 151. 213. 201.  23. 236.
 110.  40. 241.  13.  92.  62. 166. 123.  63.  31. 162. 206. 202. 101.
 146. 117.  59.  12.  60. 117.  61.  22. 130. 154.  97.  90.  56. 193.
  95. 127. 238. 139.  79.  82.  38. 197.  38.  70.  98. 187.  31.  53.
 166. 165.]
100
líY|eï|¥èÕ­P½ÝÆ2JaïZcý¼a[ÅÇd-;õóJØ,YFPcõíø̪<#aU£xú´}™èÊ2Ë«.ZVñǘÈÉ¢&íæÄMëzÛÞ²Q²ÒîG«Á21
[229. 251.  97. 205. 240. 137. 217. 131.  99. 240.  25.  92.  73.  33.
 134. 196.  49.  81.  58. 166. 190. 213.  99. 206. 215. 113.  48. 213.
 207.  57.  59. 216. 161. 133. 175. 136. 105. 103. 190.  76. 160. 205.
 186. 196. 215. 105. 138.  97. 108.  64.  30. 176. 151. 213. 201.  23.
 236. 110.  40. 241.  13.  92.  62. 166. 123.  63.  31. 162. 206. 202.
 101. 146. 117.  59.  12.  60. 

[141. 152.  81. 182. 173.  18.  87. 114. 185.  46. 231. 143.  49. 213.
 220. 242. 251.  97. 205. 240. 137. 217. 131.  99. 240.  25.  92.  73.
  33. 134. 196.  49.  81.  58. 166. 190. 213.  99. 206. 215. 113.  48.
 213. 207.  57.  59. 216. 161. 133. 175. 136. 105. 103. 190.  76. 160.
 205. 186. 196. 215. 105. 138.  97. 108.  64.  30. 176. 151. 213. 201.
  23. 236. 110.  40. 241.  13.  92.  62. 166. 123.  63.  31. 162. 206.
 202. 101. 146. 117.  59.  12.  60. 117.  61.  22. 130. 154.  97.  90.
  56. 193.  95. 127. 238. 139.  79.  82.  38. 197.  38.  70.  98. 187.
  31.  53. 166. 165.]
116
$ÝB9žãþEºs½ah~‡íY|eï|¥èÕ­P½ÝÆ2JaïZcý¼a[ÅÇd-;õóJØ,YFPcõíø̪<#aU£xú´}™èÊ2Ë«.ZVñǘÈÉ¢&íæÄMëzÛÞ²Q²ÒîG«Á21
[338.  59. 152.  81. 182. 173.  18.  87. 114. 185.  46. 231. 143.  49.
 213. 220. 242. 251.  97. 205. 240. 137. 217. 131.  99. 240.  25.  92.
  73.  33. 134. 196.  49.  81.  58. 166. 190. 213.  99. 206. 215. 113.
  48. 213. 207.  57.  59. 216. 161. 133. 175. 136. 105. 103. 190.  76.
 160.

[183. 211.  12. 136.   4. 235. 199.  77. 149.  28. 172.  42.  69. 131.
 226.  59. 152.  81. 182. 173.  18.  87. 114. 185.  46. 231. 143.  49.
 213. 220. 242. 251.  97. 205. 240. 137. 217. 131.  99. 240.  25.  92.
  73.  33. 134. 196.  49.  81.  58. 166. 190. 213.  99. 206. 215. 113.
  48. 213. 207.  57.  59. 216. 161. 133. 175. 136. 105. 103. 190.  76.
 160. 205. 186. 196. 215. 105. 138.  97. 108.  64.  30. 176. 151. 213.
 201.  23. 236. 110.  40. 241.  13.  92.  62. 166. 123.  63.  31. 162.
 206. 202. 101. 146. 117.  59.  12.  60. 117.  61.  22. 130. 154.  97.
  90.  56. 193.  95. 127. 238. 139.  79.  82.  38. 197.  38.  70.  98.
 187.  31.  53. 166. 165.]
131
C_˜wSÙ!¨8¶ÑnÇ$ÝB9žãþEºs½ah~‡íY|eï|¥èÕ­P½ÝÆ2JaïZcý¼a[ÅÇd-;õóJØ,YFPcõíø̪<#aU£xú´}™èÊ2Ë«.ZVñǘÈÉ¢&íæÄMëzÛÞ²Q²ÒîG«Á21
[237. 202. 211.  12. 136.   4. 235. 199.  77. 149.  28. 172.  42.  69.
 131. 226.  59. 152.  81. 182. 173.  18.  87. 114. 185.  46. 231. 143.
  49. 213. 220. 242. 251.  97. 205. 240. 137. 217. 131. 

[229. 181. 193.  73. 126.  98. 200.  84.  62. 170. 106.  52. 199. 202.
 211.  12. 136.   4. 235. 199.  77. 149.  28. 172.  42.  69. 131. 226.
  59. 152.  81. 182. 173.  18.  87. 114. 185.  46. 231. 143.  49. 213.
 220. 242. 251.  97. 205. 240. 137. 217. 131.  99. 240.  25.  92.  73.
  33. 134. 196.  49.  81.  58. 166. 190. 213.  99. 206. 215. 113.  48.
 213. 207.  57.  59. 216. 161. 133. 175. 136. 105. 103. 190.  76. 160.
 205. 186. 196. 215. 105. 138.  97. 108.  64.  30. 176. 151. 213. 201.
  23. 236. 110.  40. 241.  13.  92.  62. 166. 123.  63.  31. 162. 206.
 202. 101. 146. 117.  59.  12.  60. 117.  61.  22. 130. 154.  97.  90.
  56. 193.  95. 127. 238. 139.  79.  82.  38. 197.  38.  70.  98. 187.
  31.  53. 166. 165.]
144
qAMÕ
îTàÊ6öÀSV_˜wSÙ!¨8¶ÑnÇ$ÝB9žãþEºs½ah~‡íY|eï|¥èÕ­P½ÝÆ2JaïZcý¼a[ÅÇd-;õóJØ,YFPcõíø̪<#aU£xú´}™èÊ2Ë«.ZVñǘÈÉ¢&íæÄMëzÛÞ²Q²ÒîG«Á21
[215.  14. 181. 193.  73. 126.  98. 200.  84.  62. 170. 106.  52. 199.
 202. 211.  12. 136.   4. 235. 199.  77. 149.  2

[153. 199. 183. 118.  38. 125. 205. 105. 127. 131. 111.  14. 181. 193.
  73. 126.  98. 200.  84.  62. 170. 106.  52. 199. 202. 211.  12. 136.
   4. 235. 199.  77. 149.  28. 172.  42.  69. 131. 226.  59. 152.  81.
 182. 173.  18.  87. 114. 185.  46. 231. 143.  49. 213. 220. 242. 251.
  97. 205. 240. 137. 217. 131.  99. 240.  25.  92.  73.  33. 134. 196.
  49.  81.  58. 166. 190. 213.  99. 206. 215. 113.  48. 213. 207.  57.
  59. 216. 161. 133. 175. 136. 105. 103. 190.  76. 160. 205. 186. 196.
 215. 105. 138.  97. 108.  64.  30. 176. 151. 213. 201.  23. 236. 110.
  40. 241.  13.  92.  62. 166. 123.  63.  31. 162. 206. 202. 101. 146.
 117.  59.  12.  60. 117.  61.  22. 130. 154.  97.  90.  56. 193.  95.
 127. 238. 139.  79.  82.  38. 197.  38.  70.  98. 187.  31.  53. 166.
 165.]
155
%SC²	YõûšAMÕ
îTàÊ6öÀSV_˜wSÙ!¨8¶ÑnÇ$ÝB9žãþEºs½ah~‡íY|eï|¥èÕ­P½ÝÆ2JaïZcý¼a[ÅÇd-;õóJØ,YFPcõíø̪<#aU£xú´}™èÊ2Ë«.ZVñǘÈÉ¢&íæÄMëzÛÞ²Q²ÒîG«Á21
[101.  52. 199. 183. 118.  38. 125. 205. 105. 127. 1

In [61]:
test = [i for i in qq]

while len(test)>5:
    test = [(test[i]-test[i-1])%256 for i in range(1,len(test))]
    print("Try with a %d bytes length cipher text" % len(test))
    for k in range(256):
        try:
            tmp = "".join([chr((i-k)%256) for i in test])
            if "key" in tmp or "image" in tmp or "crypt" in tmp or "pass" in tmp:
                print(k,tmp)
                print(test)
        except:
            pass

Try with a 164 bytes length cipher text
Try with a 163 bytes length cipher text
Try with a 162 bytes length cipher text
Try with a 161 bytes length cipher text
Try with a 160 bytes length cipher text
Try with a 159 bytes length cipher text
Try with a 158 bytes length cipher text
Try with a 157 bytes length cipher text
Try with a 156 bytes length cipher text
Try with a 155 bytes length cipher text
Try with a 154 bytes length cipher text
Try with a 153 bytes length cipher text
Try with a 152 bytes length cipher text
Try with a 151 bytes length cipher text
Try with a 150 bytes length cipher text
Try with a 149 bytes length cipher text
Try with a 148 bytes length cipher text
116 you liked my new encryption tool, pretty secure huh, anyway here is the key to the encrypted image from /var/backups/recovery: cB!6%sdH8Lj^@Y*$C2cfˆ
[237, 227, 233, 148, 224, 221, 223, 217, 216, 148, 225, 237, 148, 226, 217, 235, 148, 217, 226, 215, 230, 237, 228, 232, 221, 227, 226, 148, 232, 227, 227, 224, 160, 1

In [25]:
test = [i for i in qq]
test = [(test[i]-test[i-1])%256 for i in range(1,len(test))]

In [26]:
test

[12,
 204,
 248,
 127,
 122,
 152,
 32,
 170,
 20,
 52,
 199,
 183,
 118,
 38,
 125,
 205,
 105,
 127,
 131,
 111,
 14,
 181,
 193,
 73,
 126,
 98,
 200,
 84,
 62,
 170,
 106,
 52,
 199,
 202,
 211,
 12,
 136,
 4,
 235,
 199,
 77,
 149,
 28,
 172,
 42,
 69,
 131,
 226,
 59,
 152,
 81,
 182,
 173,
 18,
 87,
 114,
 185,
 46,
 231,
 143,
 49,
 213,
 220,
 242,
 251,
 97,
 205,
 240,
 137,
 217,
 131,
 99,
 240,
 25,
 92,
 73,
 33,
 134,
 196,
 49,
 81,
 58,
 166,
 190,
 213,
 99,
 206,
 215,
 113,
 48,
 213,
 207,
 57,
 59,
 216,
 161,
 133,
 175,
 136,
 105,
 103,
 190,
 76,
 160,
 205,
 186,
 196,
 215,
 105,
 138,
 97,
 108,
 64,
 30,
 176,
 151,
 213,
 201,
 23,
 236,
 110,
 40,
 241,
 13,
 92,
 62,
 166,
 123,
 63,
 31,
 162,
 206,
 202,
 101,
 146,
 117,
 59,
 12,
 60,
 117,
 61,
 22,
 130,
 154,
 97,
 90,
 56,
 193,
 95,
 127,
 238,
 139,
 79,
 82,
 38,
 197,
 38,
 70,
 98,
 187,
 31,
 53,
 166,
 165]

In [41]:
mm

array([294.,  12., 204., 248., 127., 122., 152.,  32., 170.,  20.,  52.,
       199., 183., 118.,  38., 125., 205., 105., 127., 131., 111.,  14.,
       181., 193.,  73., 126.,  98., 200.,  84.,  62., 170., 106.,  52.,
       199., 202., 211.,  12., 136.,   4., 235., 199.,  77., 149.,  28.,
       172.,  42.,  69., 131., 226.,  59., 152.,  81., 182., 173.,  18.,
        87., 114., 185.,  46., 231., 143.,  49., 213., 220., 242., 251.,
        97., 205., 240., 137., 217., 131.,  99., 240.,  25.,  92.,  73.,
        33., 134., 196.,  49.,  81.,  58., 166., 190., 213.,  99., 206.,
       215., 113.,  48., 213., 207.,  57.,  59., 216., 161., 133., 175.,
       136., 105., 103., 190.,  76., 160., 205., 186., 196., 215., 105.,
       138.,  97., 108.,  64.,  30., 176., 151., 213., 201.,  23., 236.,
       110.,  40., 241.,  13.,  92.,  62., 166., 123.,  63.,  31., 162.,
       206., 202., 101., 146., 117.,  59.,  12.,  60., 117.,  61.,  22.,
       130., 154.,  97.,  90.,  56., 193.,  95., 12

In [49]:
mm[mm<0]+=256

In [50]:
mm

array([102., 127., 131., 111.,  14., 181., 193.,  73., 126.,  98., 200.,
        84.,  62., 170., 106.,  52., 199., 202., 211.,  12., 136.,   4.,
       235., 199.,  77., 149.,  28., 172.,  42.,  69., 131., 226.,  59.,
       152.,  81., 182., 173.,  18.,  87., 114., 185.,  46., 231., 143.,
        49., 213., 220., 242., 251.,  97., 205., 240., 137., 217., 131.,
        99., 240.,  25.,  92.,  73.,  33., 134., 196.,  49.,  81.,  58.,
       166., 190., 213.,  99., 206., 215., 113.,  48., 213., 207.,  57.,
        59., 216., 161., 133., 175., 136., 105., 103., 190.,  76., 160.,
       205., 186., 196., 215., 105., 138.,  97., 108.,  64.,  30., 176.,
       151., 213., 201.,  23., 236., 110.,  40., 241.,  13.,  92.,  62.,
       166., 123.,  63.,  31., 162., 206., 202., 101., 146., 117.,  59.,
        12.,  60., 117.,  61.,  22., 130., 154.,  97.,  90.,  56., 193.,
        95., 127., 238., 139.,  79.,  82.,  38., 197.,  38.,  70.,  98.,
       187.,  31.,  53., 166., 165.])

In [35]:
mm+148

array([442., 160., 352., 396., 275., 270., 300., 180., 318., 168., 200.,
       347., 331., 266., 186., 273., 353., 253., 275., 279., 259., 162.,
       329., 341., 221., 274., 246., 348., 232., 210., 318., 254., 200.,
       347., 350., 359., 160., 284., 152., 383., 347., 225., 297., 176.,
       320., 190., 217., 279., 374., 207., 300., 229., 330., 321., 166.,
       235., 262., 333., 194., 379., 291., 197., 361., 368., 390., 399.,
       245., 353., 388., 285., 365., 279., 247., 388., 173., 240., 221.,
       181., 282., 344., 197., 229., 206., 314., 338., 361., 247., 354.,
       363., 261., 196., 361., 355., 205., 207., 364., 309., 281., 323.,
       284., 253., 251., 338., 224., 308., 353., 334., 344., 363., 253.,
       286., 245., 256., 212., 178., 324., 299., 361., 349., 171., 384.,
       258., 188., 389., 161., 240., 210., 314., 271., 211., 179., 310.,
       354., 350., 249., 294., 265., 207., 160., 208., 265., 209., 170.,
       278., 302., 245., 238., 204., 341., 243., 27